name: CI

on:
  push:
    branches: [ main ]


jobs:
  unittests:
    name: Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - uses: actions/checkout@v4
      - run: dotnet test
        working-directory: LogAnalytics.Client/LogAnalytics.Client.UnitTests
  buildandpublish:
    name: Build and Publish NuGet
    needs: [unittests] # ensure we run the unit tests before we start building and packaging.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1
    - name: Wire up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
      working-directory: LogAnalytics.Client/LogAnalytics.Client
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: LogAnalytics.Client/LogAnalytics.Client
    - name: Publish LogAnalytics.Client
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: LogAnalytics.Client/LogAnalytics.Client/LogAnalytics.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_LOGANALYTICS_APIKEY}}
